### ISSUE TITLE
Deploy issue

### ISSUE THREAD

**Issue by aarongustafson** [austil/album-review#2]
```
Command: D:\home\SiteExtensions\ComposerExtension\Hooks\deploy.cmd
Install Dependencies with Composer
Could not open input file: D:\home\SiteExtensions\ComposerExtension\Commands\\composer.phar
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\58.50929.2438\bin\Scripts\starter.cmd D:\home\SiteExtensions\ComposerExtension\Hooks\deploy.cmd
```

**Comment by austil** [comment]
No problem on my side (Ubuntu Bash on Windows 😀).
So i don't now what to tell you ...

(may be try http://stackoverflow.com/questions/20769980/could-not-open-input-file-composer-phar)

**Comment by austil** [comment]
So you're using Azure and the site extension for Composer got a problem with my stuff.
The only thing I can tell you is that my app is made to be built in local and then deployed (via ftp for example).

**Comment by aarongustafson** [comment]
We got the hoe page running but Search fails: https://album-review-10kapart2016.azurewebsites.net/

**Comment by austil** [comment]
My bad : https://github.com/austil/album-review/commit/65c63206244b57dafa8163de429c99a7bfdf9a62
Should be working now.
Thx for your time.
